name=SmoothLED
version=0.0.1
author=S. Shahriar <hi@shadowshahriar.dev>
maintainer=S. Shahriar <hi@shadowshahriar.dev>
sentence=Buttery-smooth LED animations.
paragraph=This library features a non-blocking approach to animate LED brightness with various effects.
category=Signal Input/Output
url=https://github.com/ShadowShahriar/arduino-playground/tree/main/02-custom-libraries
architectures=*