name=QuickUnique
version=0.0.1
author=S. Shahriar <hi@shadowshahriar.dev>
maintainer=S. Shahriar <hi@shadowshahriar.dev>
sentence=A dead simple consecutive unique number generator.
paragraph=This library abstracts the standard random function to return consecutive unique numbers.
category=Timing
url=https://github.com/ShadowShahriar/arduino-playground/tree/main/02-custom-libraries
architectures=*