name=AdvancedInterval
version=0.0.1
author=S. Shahriar <hi@shadowshahriar.dev>
maintainer=S. Shahriar <hi@shadowshahriar.dev>
sentence=An advanced non-blocking interval libary.
paragraph=This library abstracts the non-blocking interval logic using millis and provides callback functions for interval events such as start, stop, pause, resume, and reset.
category=Timing
url=https://github.com/ShadowShahriar/arduino-playground/tree/main/02-custom-libraries
architectures=*